"""add index in workflow run

Revision ID: 02ffd7f23d1d
Revises: d1dac4c93e61
Create Date: 2026-01-29 20:36:57.924887

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02ffd7f23d1d"
down_revision: Union[str, None] = "d1dac4c93e61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_workflow_runs_campaign_id", "workflow_runs", ["campaign_id"], unique=False
    )
    op.create_index(
        "idx_workflow_runs_workflow_id", "workflow_runs", ["workflow_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_workflow_runs_workflow_id", table_name="workflow_runs")
    op.drop_index("idx_workflow_runs_campaign_id", table_name="workflow_runs")
    # ### end Alembic commands ###
