"""fix unique constraint on workflow definition

Revision ID: 0c1bbc83fe9e
Revises: 9f5f2d35f6fb
Create Date: 2025-06-04 15:56:02.979658

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c1bbc83fe9e"
down_revision: Union[str, None] = "9f5f2d35f6fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_workflow_definitions_workflow_hash", table_name="workflow_definitions"
    )
    op.create_index(
        "ix_workflow_hash_workflow_id",
        "workflow_definitions",
        ["workflow_hash", "workflow_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_workflow_hash_workflow_id",
        "workflow_definitions",
        ["workflow_hash", "workflow_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_workflow_hash_workflow_id", "workflow_definitions", type_="unique"
    )
    op.drop_index("ix_workflow_hash_workflow_id", table_name="workflow_definitions")
    op.create_index(
        "ix_workflow_definitions_workflow_hash",
        "workflow_definitions",
        ["workflow_hash"],
        unique=True,
    )
    # ### end Alembic commands ###
