"""add call disposition codes

Revision ID: 0fe708f2acb9
Revises: 1225ac786848
Create Date: 2025-07-21 14:27:42.942689

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fe708f2acb9"
down_revision: Union[str, None] = "1225ac786848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflows", sa.Column("call_disposition_codes", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "call_disposition_codes")
    # ### end Alembic commands ###
