"""add transfer_call tool category

Revision ID: 1a7d74d54e8f
Revises: 34c8537dfde5
Create Date: 2026-02-03 11:18:11.417837

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "1a7d74d54e8f"
down_revision: Union[str, None] = "34c8537dfde5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="tool_category",
        new_values=["http_api", "end_call", "transfer_call", "native", "integration"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="tools", column_name="category"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="tool_category",
        new_values=["http_api", "end_call", "native", "integration"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="tools", column_name="category"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
