"""add total call duration to usage

Revision ID: 1da1d650c0e4
Revises: ec010596a0b4
Create Date: 2025-07-08 15:41:15.039999

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1da1d650c0e4"
down_revision: Union[str, None] = "ec010596a0b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_usage_cycles",
        sa.Column(
            "total_duration_seconds",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_usage_cycles", "total_duration_seconds")
    # ### end Alembic commands ###
