"""add provider

Revision ID: 20c780c2a218
Revises: ac6da37c5034
Create Date: 2025-06-09 19:23:00.111377

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20c780c2a218"
down_revision: Union[str, None] = "ac6da37c5034"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("integrations", sa.Column("provider", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("integrations", "provider")
    # ### end Alembic commands ###
