"""add annotations in workflow run model

Revision ID: 2ed4baa89f15
Revises: cdc80a4fd2dd
Create Date: 2025-06-17 13:30:43.784644

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ed4baa89f15"
down_revision: Union[str, None] = "cdc80a4fd2dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_runs", sa.Column("annotations", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_runs", "annotations")
    # ### end Alembic commands ###
