"""add processing state in queued runs

Revision ID: 34c8537dfde5
Revises: 02ffd7f23d1d
Create Date: 2026-01-30 14:40:29.905325

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "34c8537dfde5"
down_revision: Union[str, None] = "02ffd7f23d1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.create_index("ix_api_keys_key_hash", "api_keys", ["key_hash"], unique=False)
    op.sync_enum_values(
        enum_schema="public",
        enum_name="queued_run_state",
        new_values=["queued", "processed", "processing", "failed"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="queued_runs", column_name="state"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="queued_run_state",
        new_values=["queued", "processed", "failed"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="queued_runs", column_name="state"
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_index("ix_api_keys_key_hash", table_name="api_keys")
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    # ### end Alembic commands ###
