"""add workflow configurations

Revision ID: 3717ae6146e2
Revises: f952c9c1105a
Create Date: 2025-08-19 14:41:44.852794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3717ae6146e2"
down_revision: Union[str, None] = "f952c9c1105a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflows",
        sa.Column(
            "workflow_configurations",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "workflow_configurations")
    # ### end Alembic commands ###
