"""Added livekit room

Revision ID: 3a30110d7cd7
Revises: 93a1ddbb6ffd
Create Date: 2025-04-05 15:03:00.749510

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a30110d7cd7"
down_revision: Union[str, None] = "93a1ddbb6ffd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "livekit_rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("VOICE", "TEXT", "VIDEO", name="room_type"), nullable=False
        ),
        sa.Column(
            "state",
            sa.Enum(
                "CONNECTED",
                "DISCONNECTED",
                "RECONNECTING",
                "RECONNECTED",
                name="room_state",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_livekit_rooms_id"), "livekit_rooms", ["id"], unique=False)
    op.create_index(
        op.f("ix_livekit_rooms_name"), "livekit_rooms", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_livekit_rooms_state"), "livekit_rooms", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_livekit_rooms_type"), "livekit_rooms", ["type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_livekit_rooms_type"), table_name="livekit_rooms")
    op.drop_index(op.f("ix_livekit_rooms_state"), table_name="livekit_rooms")
    op.drop_index(op.f("ix_livekit_rooms_name"), table_name="livekit_rooms")
    op.drop_index(op.f("ix_livekit_rooms_id"), table_name="livekit_rooms")
    op.drop_table("livekit_rooms")
    # ### end Alembic commands ###
