"""add selected organisation id field in user model

Revision ID: 45fa7fec2993
Revises: f6f19156bcb7
Create Date: 2025-06-09 16:00:52.209779

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45fa7fec2993"
down_revision: Union[str, None] = "f6f19156bcb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("selected_organization_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "users", "organizations", ["selected_organization_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "selected_organization_id")
    # ### end Alembic commands ###
