"""add organisation_id in workflow

Revision ID: 477b47ce346b
Revises: fec0fb9a8db7
Create Date: 2025-08-15 14:11:28.088841

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "477b47ce346b"
down_revision: Union[str, None] = "fec0fb9a8db7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflows", sa.Column("organization_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "workflows", "organizations", ["organization_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workflows", type_="foreignkey")
    op.drop_column("workflows", "organization_id")
    # ### end Alembic commands ###
