"""add teplate context variables in workflow

Revision ID: 5253971e3f03
Revises: 0c1bbc83fe9e
Create Date: 2025-06-05 14:06:51.059664

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5253971e3f03"
down_revision: Union[str, None] = "0c1bbc83fe9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflows", sa.Column("template_context_variables", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "template_context_variables")
    # ### end Alembic commands ###
