"""add campaign logs column

Revision ID: 6499c608d0f6
Revises: a2355fc6bdc1
Create Date: 2026-05-05 17:25:49.235730

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6499c608d0f6"
down_revision: Union[str, None] = "a2355fc6bdc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns",
        sa.Column(
            "logs", sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "logs")
    # ### end Alembic commands ###
