"""add status in workflow

Revision ID: 693a865c011f
Revises: 477b47ce346b
Create Date: 2025-08-15 14:27:46.748114

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "693a865c011f"
down_revision: Union[str, None] = "477b47ce346b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First create the enum type
    workflow_status_enum = sa.Enum("active", "archived", name="workflow_status")
    workflow_status_enum.create(op.get_bind(), checkfirst=True)

    # Then add the column with the enum type
    op.add_column(
        "workflows",
        sa.Column(
            "status",
            workflow_status_enum,
            nullable=False,
            server_default=sa.text("'active'"),
        ),
    )

    # Create index for better query performance
    op.create_index("ix_workflows_status", "workflows", ["status"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index first
    op.drop_index("ix_workflows_status", table_name="workflows")

    # Drop the column
    op.drop_column("workflows", "status")

    # Drop the enum type
    workflow_status_enum = sa.Enum("active", "archived", name="workflow_status")
    workflow_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
