"""add folders and workflow folder_id

Revision ID: 6bd9f67ec994
Revises: 2f638891cbb6
Create Date: 2026-05-22 12:52:30.737380

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bd9f67ec994"
down_revision: Union[str, None] = "2f638891cbb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_folder_org_name"),
    )
    op.create_index(
        op.f("ix_folders_organization_id"), "folders", ["organization_id"], unique=False
    )
    op.add_column("workflows", sa.Column("folder_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_workflows_folder_id"), "workflows", ["folder_id"], unique=False
    )
    op.create_foreign_key(
        "fk_workflows_folder_id",
        "workflows",
        "folders",
        ["folder_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_workflows_folder_id", "workflows", type_="foreignkey")
    op.drop_index(op.f("ix_workflows_folder_id"), table_name="workflows")
    op.drop_column("workflows", "folder_id")
    op.drop_index(op.f("ix_folders_organization_id"), table_name="folders")
    op.drop_table("folders")
    # ### end Alembic commands ###
