"""add price_per_second_usd

Revision ID: 7feef09d7cc6
Revises: 3717ae6146e2
Create Date: 2025-08-25 13:04:13.436156

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7feef09d7cc6"
down_revision: Union[str, None] = "3717ae6146e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("price_per_second_usd", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "price_per_second_usd")
    # ### end Alembic commands ###
