"""add is_superuser to user model

Revision ID: 9641b4f306cd
Revises: 3a0384c5ab2e
Create Date: 2025-05-07 11:37:44.295774

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9641b4f306cd"
down_revision: Union[str, None] = "3a0384c5ab2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###
