"""add storage backend in workflow

Revision ID: 982ec8e434be
Revises: d0060de90c18
Create Date: 2025-09-09 10:39:12.894626

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "982ec8e434be"
down_revision: Union[str, None] = "d0060de90c18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("s3", "minio", name="storage_backend").create(op.get_bind())
    op.drop_constraint(
        "queued_runs_workflow_run_id_fkey", "queued_runs", type_="foreignkey"
    )
    op.drop_column("queued_runs", "workflow_run_id")
    op.add_column(
        "workflow_runs",
        sa.Column(
            "storage_backend",
            postgresql.ENUM("s3", "minio", name="storage_backend", create_type=False),
            server_default=sa.text("'s3'::storage_backend"),
            nullable=False,
        ),
    )
    sa.Enum("VOICE", "TEXT", "VIDEO", name="room_type").drop(op.get_bind())
    sa.Enum(
        "CONNECTED", "DISCONNECTED", "RECONNECTING", "RECONNECTED", name="room_state"
    ).drop(op.get_bind())
    op.sync_enum_values(
        enum_schema="public",
        enum_name="workflow_run_mode",
        new_values=["twilio", "stasis", "webrtc", "smallwebrtc", "VOICE", "CHAT"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="workflow_runs", column_name="mode"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="workflow_run_mode",
        new_values=["VOICE", "CHAT", "webrtc", "smallwebrtc", "twilio", "stasis"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="workflow_runs", column_name="mode"
            )
        ],
        enum_values_to_rename=[],
    )
    sa.Enum(
        "CONNECTED", "DISCONNECTED", "RECONNECTING", "RECONNECTED", name="room_state"
    ).create(op.get_bind())
    sa.Enum("VOICE", "TEXT", "VIDEO", name="room_type").create(op.get_bind())
    op.drop_column("workflow_runs", "storage_backend")
    op.add_column(
        "queued_runs",
        sa.Column("workflow_run_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "queued_runs_workflow_run_id_fkey",
        "queued_runs",
        "workflow_runs",
        ["workflow_run_id"],
        ["id"],
    )
    sa.Enum("s3", "minio", name="storage_backend").drop(op.get_bind())
    # ### end Alembic commands ###
