"""add recording and transcript urls in workflow run

Revision ID: 9be6240baa00
Revises: 9641b4f306cd
Create Date: 2025-05-09 21:50:03.369283

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9be6240baa00"
down_revision: Union[str, None] = "9641b4f306cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_runs", sa.Column("is_completed", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "workflow_runs", sa.Column("recording_url", sa.String(), nullable=True)
    )
    op.add_column(
        "workflow_runs", sa.Column("transcript_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_runs", "transcript_url")
    op.drop_column("workflow_runs", "recording_url")
    op.drop_column("workflow_runs", "is_completed")
    # ### end Alembic commands ###
