"""add workflow id in workflow definition

Revision ID: 9ef49df72862
Revises: 58f17b468b3c
Create Date: 2025-06-04 10:54:01.714149

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ef49df72862"
down_revision: Union[str, None] = "58f17b468b3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_definitions", sa.Column("workflow_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "workflow_definitions", "workflows", ["workflow_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workflow_definitions", type_="foreignkey")
    op.drop_column("workflow_definitions", "workflow_id")
    # ### end Alembic commands ###
