"""remove workflow definition id from workflow

Revision ID: 9f5f2d35f6fb
Revises: 9ef49df72862
Create Date: 2025-06-04 13:27:45.776741

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f5f2d35f6fb"
down_revision: Union[str, None] = "9ef49df72862"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_definitions",
        sa.Column(
            "is_current", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.drop_constraint(
        "workflows_current_definition_id_fkey", "workflows", type_="foreignkey"
    )
    op.drop_column("workflows", "current_definition_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflows",
        sa.Column(
            "current_definition_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "workflows_current_definition_id_fkey",
        "workflows",
        "workflow_definitions",
        ["current_definition_id"],
        ["id"],
    )
    op.drop_column("workflow_definitions", "is_current")
    # ### end Alembic commands ###
