"""add last validated at

Revision ID: a29b05f31ddf
Revises: 9be6240baa00
Create Date: 2025-05-21 22:59:27.008241

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a29b05f31ddf"
down_revision: Union[str, None] = "9be6240baa00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_configurations",
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_configurations", "last_validated_at")
    # ### end Alembic commands ###
