"""add usage info

Revision ID: a2b092ff7282
Revises: a29b05f31ddf
Create Date: 2025-05-29 20:25:37.110818

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2b092ff7282"
down_revision: Union[str, None] = "a29b05f31ddf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_runs", sa.Column("usage_info", sa.JSON(), nullable=True))
    op.add_column("workflow_runs", sa.Column("cost_info", sa.JSON(), nullable=True))
    op.add_column(
        "workflow_runs", sa.Column("initial_context", sa.JSON(), nullable=True)
    )
    op.add_column(
        "workflow_runs", sa.Column("gathered_context", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_runs", "gathered_context")
    op.drop_column("workflow_runs", "initial_context")
    op.drop_column("workflow_runs", "cost_info")
    op.drop_column("workflow_runs", "usage_info")
    # ### end Alembic commands ###
