"""add log in workflow run model

Revision ID: a75ae71af479
Revises: 13ccd6e1f5ad
Create Date: 2025-08-05 22:37:06.248630

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a75ae71af479"
down_revision: Union[str, None] = "13ccd6e1f5ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_runs",
        sa.Column(
            "logs",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_runs", "logs")
    # ### end Alembic commands ###
