"""add created by in integration

Revision ID: ac6da37c5034
Revises: d666f3244648
Create Date: 2025-06-09 17:27:37.088950

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac6da37c5034"
down_revision: Union[str, None] = "d666f3244648"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("integrations", sa.Column("created_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "integrations", "users", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "integrations", type_="foreignkey")
    op.drop_column("integrations", "created_by")
    # ### end Alembic commands ###
