"""add columns in usage table

Revision ID: c425d3445750
Revises: 7feef09d7cc6
Create Date: 2025-08-25 13:37:15.524965

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c425d3445750"
down_revision: Union[str, None] = "7feef09d7cc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DEPRECATED_QUOTA_COMMENT = "Deprecated. MPS owns quota and credit ledger state."


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_usage_cycles",
        sa.Column("used_amount_usd", sa.Float(), nullable=True),
    )
    op.add_column(
        "organization_usage_cycles",
        sa.Column(
            "quota_amount_usd",
            sa.Float(),
            nullable=True,
            comment=DEPRECATED_QUOTA_COMMENT,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_usage_cycles", "quota_amount_usd")
    op.drop_column("organization_usage_cycles", "used_amount_usd")
    # ### end Alembic commands ###
