"""add template description

Revision ID: cdc80a4fd2dd
Revises: 7e90cc8d025b
Create Date: 2025-06-10 18:31:30.952698

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdc80a4fd2dd"
down_revision: Union[str, None] = "7e90cc8d025b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_templates",
        sa.Column("template_description", sa.String(), nullable=False),
    )
    op.create_index(
        op.f("ix_workflow_templates_template_description"),
        "workflow_templates",
        ["template_description"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_templates_template_description"),
        table_name="workflow_templates",
    )
    op.drop_column("workflow_templates", "template_description")
    # ### end Alembic commands ###
