"""add connection details

Revision ID: d11fbd083a55
Revises: 20c780c2a218
Create Date: 2025-06-09 19:49:24.999108

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d11fbd083a55"
down_revision: Union[str, None] = "20c780c2a218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "integrations", sa.Column("connection_details", sa.JSON(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("integrations", "connection_details")
    # ### end Alembic commands ###
