"""remove unique tool name constraint

Revision ID: dcb0a27d98c6
Revises: 493ca2bb001f
Create Date: 2026-01-14 16:07:01.940879

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcb0a27d98c6"
down_revision: Union[str, None] = "493ca2bb001f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("unique_org_tool_name"), "tools", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("unique_org_tool_name"),
        "tools",
        ["organization_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
