"""add_looptalk_testing_tables_without_turns

Revision ID: e0d1a9b9f6c4
Revises: 2ed4baa89f15
Create Date: 2025-07-01 14:29:12.081935

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0d1a9b9f6c4"
down_revision: Union[str, None] = "2ed4baa89f15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "looptalk_test_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "completed", "failed", name="test_session_status"
            ),
            nullable=False,
        ),
        sa.Column("actor_workflow_id", sa.Integer(), nullable=False),
        sa.Column("adversary_workflow_id", sa.Integer(), nullable=False),
        sa.Column("load_test_group_id", sa.String(), nullable=True),
        sa.Column("test_index", sa.Integer(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_workflow_id"],
            ["workflows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["adversary_workflow_id"],
            ["workflows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_looptalk_test_sessions_group_id",
        "looptalk_test_sessions",
        ["load_test_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_looptalk_test_sessions_id"),
        "looptalk_test_sessions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_looptalk_test_sessions_load_test_group_id"),
        "looptalk_test_sessions",
        ["load_test_group_id"],
        unique=False,
    )
    op.create_index(
        "ix_looptalk_test_sessions_org_id",
        "looptalk_test_sessions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_looptalk_test_sessions_status",
        "looptalk_test_sessions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "looptalk_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_session_id", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("actor_recording_url", sa.String(), nullable=True),
        sa.Column("adversary_recording_url", sa.String(), nullable=True),
        sa.Column("combined_recording_url", sa.String(), nullable=True),
        sa.Column("transcript", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_session_id"],
            ["looptalk_test_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_looptalk_conversations_id"),
        "looptalk_conversations",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_looptalk_conversations_session_id",
        "looptalk_conversations",
        ["test_session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_looptalk_conversations_session_id", table_name="looptalk_conversations"
    )
    op.drop_index(
        op.f("ix_looptalk_conversations_id"), table_name="looptalk_conversations"
    )
    op.drop_table("looptalk_conversations")
    op.drop_index(
        "ix_looptalk_test_sessions_status", table_name="looptalk_test_sessions"
    )
    op.drop_index(
        "ix_looptalk_test_sessions_org_id", table_name="looptalk_test_sessions"
    )
    op.drop_index(
        op.f("ix_looptalk_test_sessions_load_test_group_id"),
        table_name="looptalk_test_sessions",
    )
    op.drop_index(
        op.f("ix_looptalk_test_sessions_id"), table_name="looptalk_test_sessions"
    )
    op.drop_index(
        "ix_looptalk_test_sessions_group_id", table_name="looptalk_test_sessions"
    )
    op.drop_table("looptalk_test_sessions")
    # ### end Alembic commands ###
