"""add recording table

Revision ID: e54ddb048535
Revises: 6fd8fac02883
Create Date: 2026-03-12 19:21:53.729888

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e54ddb048535"
down_revision: Union[str, None] = "6fd8fac02883"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("s3", "minio", name="recording_storage_backend").create(op.get_bind())
    op.create_table(
        "workflow_recordings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.String(length=16), nullable=False),
        sa.Column("workflow_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("tts_provider", sa.String(), nullable=False),
        sa.Column("tts_model", sa.String(), nullable=False),
        sa.Column("tts_voice_id", sa.String(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column(
            "storage_backend",
            postgresql.ENUM(
                "s3", "minio", name="recording_storage_backend", create_type=False
            ),
            server_default=sa.text("'s3'::recording_storage_backend"),
            nullable=False,
        ),
        sa.Column(
            "recording_metadata",
            sa.JSON(),
            server_default=sa.text("'{}'::json"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workflow_recordings_org_id",
        "workflow_recordings",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_recordings_recording_id"),
        "workflow_recordings",
        ["recording_id"],
        unique=True,
    )
    op.create_index(
        "ix_workflow_recordings_tts_scope",
        "workflow_recordings",
        ["workflow_id", "tts_provider", "tts_model", "tts_voice_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_recordings_workflow_id",
        "workflow_recordings",
        ["workflow_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_workflow_recordings_workflow_id", table_name="workflow_recordings"
    )
    op.drop_index("ix_workflow_recordings_tts_scope", table_name="workflow_recordings")
    op.drop_index(
        op.f("ix_workflow_recordings_recording_id"), table_name="workflow_recordings"
    )
    op.drop_index("ix_workflow_recordings_org_id", table_name="workflow_recordings")
    op.drop_table("workflow_recordings")
    sa.Enum("s3", "minio", name="recording_storage_backend").drop(op.get_bind())
    # ### end Alembic commands ###
