"""add failed state to queued runs

Revision ID: f952c9c1105a
Revises: 693a865c011f
Create Date: 2025-08-16 17:32:47.877340

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f952c9c1105a"
down_revision: Union[str, None] = "693a865c011f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workflows_status", table_name="workflows")
    op.execute("ALTER TYPE queued_run_state ADD VALUE IF NOT EXISTS 'failed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_workflows_status", "workflows", ["status"], unique=False)
    # ### end Alembic commands ###
