SMALLEST_TTS_MODELS = ("lightning_v3.1", "lightning_v3.1_pro")
SMALLEST_TTS_VOICES = (
    "sophia",
    "avery",
    "liam",
    "lucas",
    "olivia",
    "ryan",
    "freya",
    "william",
    "devansh",
    "arjun",
    "niharika",
    "maya",
    "dhruv",
    "mia",
    "maithili",
)
# Premium voices for lightning_v3.1_pro (American, British, Indian accents; English + Hindi only)
SMALLEST_TTS_PRO_VOICES = (
    "meher",
    "rhea",
    "aviraj",
    "cressida",
    "willow",
    "maverick",
)
SMALLEST_TTS_LANGUAGES = (
    "en",
    "hi",
    "fr",
    "de",
    "es",
    "it",
    "nl",
    "pl",
    "ru",
    "ar",
    "bn",
    "gu",
    "he",
    "kn",
    "mr",
    "ta",
)
