/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/telephony/initiate-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate Call
         * @description Initiate a call using the configured telephony provider from web browser. This is
         *     supposed to be a test call method for the draft version of the agent.
         */
        post: operations["initiate_call_api_v1_telephony_initiate_call_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/create/definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Workflow
         * @description Create a new workflow from the client
         *
         *     Args:
         *         request: The create workflow request
         *         user: The user to create the workflow for
         */
        post: operations["create_workflow_api_v1_workflow_create_definition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workflows
         * @description Get all workflows for the authenticated user's organization.
         *
         *     Returns a lightweight response with only essential fields for listing.
         *     Use GET /workflow/fetch/{workflow_id} to get full workflow details.
         */
        get: operations["get_workflows_api_v1_workflow_fetch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/fetch/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workflow
         * @description Get a single workflow by ID.
         *
         *     If a draft version exists, returns the draft content for editing.
         *     Otherwise returns the published version's content.
         */
        get: operations["get_workflow_api_v1_workflow_fetch__workflow_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Workflow
         * @description Update an existing workflow.
         *
         *     Args:
         *         workflow_id: The ID of the workflow to update
         *         request: The update request containing the new name and workflow definition
         *
         *     Returns:
         *         The updated workflow
         *
         *     Raises:
         *         HTTPException: If the workflow is not found or if there's a database error
         */
        put: operations["update_workflow_api_v1_workflow__workflow_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Credentials
         * @description List all webhook credentials for the user's organization.
         *
         *     Returns:
         *         List of credentials (without sensitive data)
         */
        get: operations["list_credentials_api_v1_credentials__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tools
         * @description List all tools for the user's organization.
         *
         *     Args:
         *         status: Optional filter by status (active, archived, draft)
         *         category: Optional filter by category (http_api, native, integration)
         *
         *     Returns:
         *         List of tools
         */
        get: operations["list_tools_api_v1_tools__get"];
        put?: never;
        /**
         * Create Tool
         * @description Create a new tool.
         *
         *     Args:
         *         request: The tool creation request
         *
         *     Returns:
         *         The created tool
         */
        post: operations["create_tool_api_v1_tools__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-base/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List documents
         * @description List all documents for the user's organization.
         *
         *     Access Control:
         *     * Users can only see documents from their organization.
         */
        get: operations["list_documents_api_v1_knowledge_base_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow-recordings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recordings
         * @description List recordings for the organization, optionally filtered.
         */
        get: operations["list_recordings_api_v1_workflow_recordings__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Node Types
         * @description List every registered NodeSpec.
         *
         *     SDK clients should pin to `spec_version` and warn if the server reports
         *     a higher version than what they were generated against.
         */
        get: operations["list_node_types_api_v1_node_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-types/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node Type */
        get: operations["get_node_type_api_v1_node_types__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CalculatorToolDefinition
         * @description Tool definition for Calculator tools.
         */
        CalculatorToolDefinition: {
            /**
             * Schema Version
             * @description Schema version.
             * @default 1
             */
            schema_version: number;
            /**
             * @description Tool type. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "calculator";
        };
        /** CallDispositionCodes */
        CallDispositionCodes: {
            /**
             * Disposition Codes
             * @default []
             */
            disposition_codes: string[];
        };
        /**
         * CreateToolRequest
         * @description Request schema for creating a reusable tool.
         */
        CreateToolRequest: {
            /**
             * Name
             * @description Display name for the tool.
             */
            name: string;
            /**
             * Description
             * @description Description shown to the agent when deciding whether to call it.
             */
            description?: string | null;
            /**
             * Category
             * @description Tool category. Must match definition.type.
             * @default http_api
             * @enum {string}
             */
            category: "http_api" | "end_call" | "transfer_call" | "calculator" | "native" | "integration" | "mcp";
            /**
             * Icon
             * @description Lucide icon identifier.
             * @default globe
             */
            icon: string | null;
            /**
             * Icon Color
             * @description Hex color for the tool icon.
             * @default #3B82F6
             */
            icon_color: string | null;
            /**
             * Definition
             * @description Typed tool definition.
             */
            definition: components["schemas"]["HttpApiToolDefinition"] | components["schemas"]["EndCallToolDefinition"] | components["schemas"]["TransferCallToolDefinition"] | components["schemas"]["CalculatorToolDefinition"] | components["schemas"]["McpToolDefinition"];
        };
        /** CreateWorkflowRequest */
        CreateWorkflowRequest: {
            /** Name */
            name: string;
            /** Workflow Definition */
            workflow_definition: {
                [key: string]: unknown;
            };
        };
        /**
         * CreatedByResponse
         * @description Response schema for the user who created a tool.
         */
        CreatedByResponse: {
            /** Id */
            id: number;
            /** Provider Id */
            provider_id: string;
        };
        /**
         * CredentialResponse
         * @description Response schema for a webhook credential (never includes sensitive data).
         */
        CredentialResponse: {
            /** Uuid */
            uuid: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Credential Type */
            credential_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * DisplayOptions
         * @description Conditional visibility rules.
         *
         *     `show` keys are AND-combined: this property is visible only when EVERY
         *     referenced field's value matches one of the listed values.
         *
         *     `hide` keys are OR-combined: this property is hidden when ANY referenced
         *     field's value matches one of the listed values.
         *
         *     Example:
         *         DisplayOptions(show={"extraction_enabled": [True]})
         *         DisplayOptions(show={"greeting_type": ["audio"]})
         */
        DisplayOptions: {
            /** Show */
            show?: {
                [key: string]: unknown[];
            } | null;
            /** Hide */
            hide?: {
                [key: string]: unknown[];
            } | null;
        };
        /**
         * DocumentListResponseSchema
         * @description Response schema for list of documents.
         */
        DocumentListResponseSchema: {
            /** Documents */
            documents: components["schemas"]["DocumentResponseSchema"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * DocumentResponseSchema
         * @description Response schema for document metadata.
         */
        DocumentResponseSchema: {
            /** Id */
            id: number;
            /** Document Uuid */
            document_uuid: string;
            /** Filename */
            filename: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** File Hash */
            file_hash: string;
            /** Mime Type */
            mime_type: string;
            /** Processing Status */
            processing_status: string;
            /** Processing Error */
            processing_error?: string | null;
            /** Total Chunks */
            total_chunks: number;
            /**
             * Retrieval Mode
             * @default chunked
             */
            retrieval_mode: string;
            /** Custom Metadata */
            custom_metadata: {
                [key: string]: unknown;
            };
            /** Docling Metadata */
            docling_metadata: {
                [key: string]: unknown;
            };
            /** Source Url */
            source_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Organization Id */
            organization_id: number;
            /** Created By */
            created_by: number;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * EndCallConfig
         * @description Configuration for End Call tools.
         */
        EndCallConfig: {
            /**
             * Messagetype
             * @description Type of goodbye message.
             * @default none
             * @enum {string}
             */
            messageType: "none" | "custom" | "audio";
            /**
             * Custommessage
             * @description Custom message to play before ending the call.
             */
            customMessage?: string | null;
            /**
             * Audiorecordingid
             * @description Recording ID for audio goodbye message.
             */
            audioRecordingId?: string | null;
            /**
             * Endcallreason
             * @description When enabled, the model must provide a reason for ending the call. The reason is set as call disposition and added to call tags.
             * @default false
             */
            endCallReason: boolean;
            /**
             * Endcallreasondescription
             * @description Description shown to the model for the reason parameter. Used only when endCallReason is enabled.
             */
            endCallReasonDescription?: string | null;
        };
        /**
         * EndCallToolDefinition
         * @description Tool definition for End Call tools.
         */
        EndCallToolDefinition: {
            /**
             * Schema Version
             * @description Schema version.
             * @default 1
             */
            schema_version: number;
            /**
             * @description Tool type. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "end_call";
            /** @description End Call configuration. */
            config: components["schemas"]["EndCallConfig"];
        };
        /**
         * GraphConstraints
         * @description Per-node-type graph rules. WorkflowGraph enforces these at validation.
         */
        GraphConstraints: {
            /** Min Incoming */
            min_incoming?: number | null;
            /** Max Incoming */
            max_incoming?: number | null;
            /** Min Outgoing */
            min_outgoing?: number | null;
            /** Max Outgoing */
            max_outgoing?: number | null;
            /** Min Instances */
            min_instances?: number | null;
            /** Max Instances */
            max_instances?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HttpApiConfig
         * @description Configuration for HTTP API tools.
         */
        HttpApiConfig: {
            /**
             * Method
             * @description HTTP method to use for the request.
             * @enum {string}
             */
            method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
            /**
             * Url
             * @description Target HTTP or HTTPS URL.
             */
            url: string;
            /**
             * Headers
             * @description Static headers to include with every request.
             */
            headers?: {
                [key: string]: string;
            } | null;
            /**
             * Credential Uuid
             * @description Reference to an external credential for request authentication.
             */
            credential_uuid?: string | null;
            /**
             * Parameters
             * @description Parameters the model must provide when calling this tool.
             */
            parameters?: components["schemas"]["ToolParameter"][] | null;
            /**
             * Preset Parameters
             * @description Parameters injected by Dograh from fixed values or workflow context templates.
             */
            preset_parameters?: components["schemas"]["PresetToolParameter"][] | null;
            /**
             * Timeout Ms
             * @description Request timeout in milliseconds.
             * @default 5000
             */
            timeout_ms: number | null;
            /**
             * Custommessage
             * @description Custom message to play after tool execution.
             */
            customMessage?: string | null;
            /**
             * Custommessagetype
             * @description Type of custom message.
             */
            customMessageType?: ("text" | "audio") | null;
            /**
             * Custommessagerecordingid
             * @description Recording ID for an audio custom message.
             */
            customMessageRecordingId?: string | null;
        };
        /**
         * HttpApiToolDefinition
         * @description Tool definition for HTTP API tools.
         */
        HttpApiToolDefinition: {
            /**
             * Schema Version
             * @description Schema version.
             * @default 1
             */
            schema_version: number;
            /**
             * @description Tool type. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "http_api";
            /** @description HTTP API configuration. */
            config: components["schemas"]["HttpApiConfig"];
        };
        /** InitiateCallRequest */
        InitiateCallRequest: {
            /** Workflow Id */
            workflow_id: number;
            /** Workflow Run Id */
            workflow_run_id?: number | null;
            /** Phone Number */
            phone_number?: string | null;
            /** Telephony Configuration Id */
            telephony_configuration_id?: number | null;
            /** From Phone Number Id */
            from_phone_number_id?: number | null;
        };
        /**
         * McpToolConfig
         * @description Configuration for a customer MCP server tool definition.
         */
        McpToolConfig: {
            /**
             * Transport
             * @description MCP transport protocol.
             * @default streamable_http
             * @constant
             */
            transport: "streamable_http";
            /**
             * Url
             * @description MCP server URL. Must use http:// or https://.
             */
            url: string;
            /**
             * Credential Uuid
             * @description Reference to an external credential for MCP server auth.
             */
            credential_uuid?: string | null;
            /**
             * Tools Filter
             * @description Allowlist of MCP tool names to expose. Empty exposes all tools.
             */
            tools_filter?: string[];
            /**
             * Timeout Secs
             * @description Connection timeout in seconds.
             * @default 30
             */
            timeout_secs: number;
            /**
             * Sse Read Timeout Secs
             * @description SSE read timeout in seconds.
             * @default 300
             */
            sse_read_timeout_secs: number;
            /**
             * Discovered Tools
             * @description Server-managed cache of the MCP server's tool catalog [{name, description}]. Populated best-effort by the backend.
             */
            discovered_tools?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * McpToolDefinition
         * @description Persisted MCP tool definition.
         */
        McpToolDefinition: {
            /**
             * Schema Version
             * @description Schema version.
             * @default 1
             */
            schema_version: number;
            /**
             * @description Tool type. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "mcp";
            /** @description MCP server configuration. */
            config: components["schemas"]["McpToolConfig"];
        };
        /**
         * NodeCategory
         * @description Drives grouping in the AddNodePanel UI.
         * @enum {string}
         */
        NodeCategory: "call_node" | "global_node" | "trigger" | "integration";
        /**
         * NodeExample
         * @description A worked example LLMs can pattern-match. Keep small and realistic.
         */
        NodeExample: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * NodeSpec
         * @description Single source of truth for a node type.
         */
        NodeSpec: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /**
             * Description
             * @description Human-facing explanation shown in AddNodePanel.
             */
            description: string;
            /**
             * Llm Hint
             * @description LLM-only guidance; omitted from the UI.
             */
            llm_hint?: string | null;
            category: components["schemas"]["NodeCategory"];
            /** Icon */
            icon: string;
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
            /** Properties */
            properties: components["schemas"]["PropertySpec"][];
            /** Examples */
            examples?: components["schemas"]["NodeExample"][];
            graph_constraints?: components["schemas"]["GraphConstraints"] | null;
        };
        /** NodeTypesResponse */
        NodeTypesResponse: {
            /** Spec Version */
            spec_version: string;
            /** Node Types */
            node_types: components["schemas"]["NodeSpec"][];
        };
        /**
         * NumberInputOptions
         * @description Renderer hints for numeric inputs.
         */
        NumberInputOptions: {
            /**
             * Fractional
             * @description Allow arbitrary fractional values via step='any'.
             * @default false
             */
            fractional: boolean;
        };
        /**
         * PresetToolParameter
         * @description A parameter injected by Dograh at runtime.
         */
        PresetToolParameter: {
            /**
             * Name
             * @description Parameter name used as a key in the request body.
             */
            name: string;
            /**
             * Type
             * @description JSON type for the resolved value.
             * @enum {string}
             */
            type: "string" | "number" | "boolean" | "object" | "array";
            /**
             * Value Template
             * @description Fixed value or template, e.g. {{initial_context.phone_number}}.
             */
            value_template: string;
            /**
             * Required
             * @description Whether the parameter must resolve to a non-empty value.
             * @default true
             */
            required: boolean;
        };
        /**
         * PropertyLayoutOptions
         * @description Renderer layout hints for a property in the node editor.
         */
        PropertyLayoutOptions: {
            /**
             * Column Span
             * @description Number of columns to occupy in the editor's 12-column grid.
             */
            column_span?: number | null;
        };
        /**
         * PropertyOption
         * @description An option in an `options` or `multi_options` dropdown.
         */
        PropertyOption: {
            /** Value */
            value: string | number | boolean;
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
        };
        /**
         * PropertyRendererOptions
         * @description Typed renderer metadata for node properties.
         *
         *     Add new renderer behavior here instead of using free-form property metadata.
         */
        PropertyRendererOptions: {
            layout?: components["schemas"]["PropertyLayoutOptions"] | null;
            number_input?: components["schemas"]["NumberInputOptions"] | null;
        };
        /**
         * PropertySpec
         * @description Single field on a node.
         *
         *     `description` is HUMAN-FACING — shown under the field in the edit
         *     dialog. Keep it concise and explain what the field does.
         *
         *     `llm_hint` is LLM-FACING — appears only in the `get_node_type` MCP
         *     response and in SDK schema output. Use it for catalog tool references
         *     (e.g., "Use `list_recordings`"), array shape, expected value idioms,
         *     or anything that would be noise in the UI. Optional; omit when the
         *     `description` already suffices for both audiences.
         */
        PropertySpec: {
            /** Name */
            name: string;
            type: components["schemas"]["PropertyType"];
            /** Display Name */
            display_name: string;
            /**
             * Description
             * @description Human-facing explanation shown in the UI.
             */
            description: string;
            /**
             * Llm Hint
             * @description LLM-only guidance; omitted from the UI.
             */
            llm_hint?: string | null;
            /** Default */
            default?: unknown;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /** Placeholder */
            placeholder?: string | null;
            display_options?: components["schemas"]["DisplayOptions"] | null;
            /** Options */
            options?: components["schemas"]["PropertyOption"][] | null;
            /** Properties */
            properties?: components["schemas"]["PropertySpec"][] | null;
            /** Min Value */
            min_value?: number | null;
            /** Max Value */
            max_value?: number | null;
            /** Min Length */
            min_length?: number | null;
            /** Max Length */
            max_length?: number | null;
            /** Pattern */
            pattern?: string | null;
            /** Editor */
            editor?: string | null;
            renderer_options?: components["schemas"]["PropertyRendererOptions"] | null;
        };
        /**
         * PropertyType
         * @description Bounded vocabulary of property types the renderer dispatches on.
         *
         *     Adding a value here requires a matching arm in the frontend
         *     `<PropertyInput>` switch and (where relevant) the SDK codegen template.
         * @enum {string}
         */
        PropertyType: "string" | "number" | "boolean" | "options" | "multi_options" | "fixed_collection" | "json" | "tool_refs" | "document_refs" | "recording_ref" | "credential_ref" | "mention_textarea" | "url";
        /**
         * RecordingListResponseSchema
         * @description Response schema for list of recordings.
         */
        RecordingListResponseSchema: {
            /** Recordings */
            recordings: components["schemas"]["RecordingResponseSchema"][];
            /** Total */
            total: number;
        };
        /**
         * RecordingResponseSchema
         * @description Response schema for a single recording.
         */
        RecordingResponseSchema: {
            /** Id */
            id: number;
            /** Recording Id */
            recording_id: string;
            /** Workflow Id */
            workflow_id?: number | null;
            /** Organization Id */
            organization_id: number;
            /** Tts Provider */
            tts_provider?: string | null;
            /** Tts Model */
            tts_model?: string | null;
            /** Tts Voice Id */
            tts_voice_id?: string | null;
            /** Transcript */
            transcript: string;
            /** Storage Key */
            storage_key: string;
            /** Storage Backend */
            storage_backend: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Created By */
            created_by: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * ToolParameter
         * @description A parameter that the tool accepts from the model at call time.
         */
        ToolParameter: {
            /**
             * Name
             * @description Parameter name used as a key in the tool request body.
             */
            name: string;
            /**
             * Type
             * @description JSON type for the parameter value.
             * @enum {string}
             */
            type: "string" | "number" | "boolean" | "object" | "array";
            /**
             * Description
             * @description Description shown to the model for this parameter.
             */
            description: string;
            /**
             * Required
             * @description Whether this parameter is required when the tool is called.
             * @default true
             */
            required: boolean;
        };
        /**
         * ToolResponse
         * @description Response schema for a reusable tool.
         */
        ToolResponse: {
            /** Id */
            id: number;
            /** Tool Uuid */
            tool_uuid: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Category */
            category: string;
            /** Icon */
            icon: string | null;
            /** Icon Color */
            icon_color: string | null;
            /** Status */
            status: string;
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
            created_by?: components["schemas"]["CreatedByResponse"] | null;
        };
        /**
         * TransferCallConfig
         * @description Configuration for Transfer Call tools.
         */
        TransferCallConfig: {
            /**
             * Destination
             * @description Phone number, SIP endpoint, or template to transfer the call to, e.g. +1234567890, PJSIP/1234, or {{initial_context.transfer_destination}}.
             */
            destination: string;
            /**
             * Messagetype
             * @description Type of message to play before transfer.
             * @default none
             * @enum {string}
             */
            messageType: "none" | "custom" | "audio";
            /**
             * Custommessage
             * @description Custom message to play before transferring.
             */
            customMessage?: string | null;
            /**
             * Audiorecordingid
             * @description Recording ID for audio message before transfer.
             */
            audioRecordingId?: string | null;
            /**
             * Timeout
             * @description Maximum seconds to wait for the destination to answer.
             * @default 30
             */
            timeout: number;
        };
        /**
         * TransferCallToolDefinition
         * @description Tool definition for Transfer Call tools.
         */
        TransferCallToolDefinition: {
            /**
             * Schema Version
             * @description Schema version.
             * @default 1
             */
            schema_version: number;
            /**
             * @description Tool type. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "transfer_call";
            /** @description Transfer Call configuration. */
            config: components["schemas"]["TransferCallConfig"];
        };
        /** UpdateWorkflowRequest */
        UpdateWorkflowRequest: {
            /** Name */
            name?: string | null;
            /** Workflow Definition */
            workflow_definition?: {
                [key: string]: unknown;
            } | null;
            /** Template Context Variables */
            template_context_variables?: {
                [key: string]: unknown;
            } | null;
            /** Workflow Configurations */
            workflow_configurations?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowListResponse
         * @description Lightweight response for workflow listings (excludes large fields).
         */
        WorkflowListResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Total Runs */
            total_runs: number;
            /** Folder Id */
            folder_id?: number | null;
            /** Workflow Uuid */
            workflow_uuid?: string | null;
        };
        /** WorkflowResponse */
        WorkflowResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Workflow Definition */
            workflow_definition: {
                [key: string]: unknown;
            };
            /** Current Definition Id */
            current_definition_id: number | null;
            /** Template Context Variables */
            template_context_variables?: {
                [key: string]: unknown;
            } | null;
            call_disposition_codes?: components["schemas"]["CallDispositionCodes"] | null;
            /** Total Runs */
            total_runs?: number | null;
            /** Workflow Configurations */
            workflow_configurations?: {
                [key: string]: unknown;
            } | null;
            /** Version Number */
            version_number?: number | null;
            /** Version Status */
            version_status?: string | null;
            /** Workflow Uuid */
            workflow_uuid?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type CalculatorToolDefinition = components['schemas']['CalculatorToolDefinition'];
export type CallDispositionCodes = components['schemas']['CallDispositionCodes'];
export type CreateToolRequest = components['schemas']['CreateToolRequest'];
export type CreateWorkflowRequest = components['schemas']['CreateWorkflowRequest'];
export type CreatedByResponse = components['schemas']['CreatedByResponse'];
export type CredentialResponse = components['schemas']['CredentialResponse'];
export type DisplayOptions = components['schemas']['DisplayOptions'];
export type DocumentListResponseSchema = components['schemas']['DocumentListResponseSchema'];
export type DocumentResponseSchema = components['schemas']['DocumentResponseSchema'];
export type EndCallConfig = components['schemas']['EndCallConfig'];
export type EndCallToolDefinition = components['schemas']['EndCallToolDefinition'];
export type GraphConstraints = components['schemas']['GraphConstraints'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type HttpApiConfig = components['schemas']['HttpApiConfig'];
export type HttpApiToolDefinition = components['schemas']['HttpApiToolDefinition'];
export type InitiateCallRequest = components['schemas']['InitiateCallRequest'];
export type McpToolConfig = components['schemas']['McpToolConfig'];
export type McpToolDefinition = components['schemas']['McpToolDefinition'];
export type NodeCategory = components['schemas']['NodeCategory'];
export type NodeExample = components['schemas']['NodeExample'];
export type NodeSpec = components['schemas']['NodeSpec'];
export type NodeTypesResponse = components['schemas']['NodeTypesResponse'];
export type NumberInputOptions = components['schemas']['NumberInputOptions'];
export type PresetToolParameter = components['schemas']['PresetToolParameter'];
export type PropertyLayoutOptions = components['schemas']['PropertyLayoutOptions'];
export type PropertyOption = components['schemas']['PropertyOption'];
export type PropertyRendererOptions = components['schemas']['PropertyRendererOptions'];
export type PropertySpec = components['schemas']['PropertySpec'];
export type PropertyType = components['schemas']['PropertyType'];
export type RecordingListResponseSchema = components['schemas']['RecordingListResponseSchema'];
export type RecordingResponseSchema = components['schemas']['RecordingResponseSchema'];
export type ToolParameter = components['schemas']['ToolParameter'];
export type ToolResponse = components['schemas']['ToolResponse'];
export type TransferCallConfig = components['schemas']['TransferCallConfig'];
export type TransferCallToolDefinition = components['schemas']['TransferCallToolDefinition'];
export type UpdateWorkflowRequest = components['schemas']['UpdateWorkflowRequest'];
export type ValidationError = components['schemas']['ValidationError'];
export type WorkflowListResponse = components['schemas']['WorkflowListResponse'];
export type WorkflowResponse = components['schemas']['WorkflowResponse'];
export type $defs = Record<string, never>;
export interface operations {
    initiate_call_api_v1_telephony_initiate_call_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiateCallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workflow_api_v1_workflow_create_definition_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflows_api_v1_workflow_fetch_get: {
        parameters: {
            query?: {
                /** @description Filter by status - can be single value (active/archived) or comma-separated (active,archived) */
                status?: string | null;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListResponse"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_api_v1_workflow_fetch__workflow_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                workflow_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workflow_api_v1_workflow__workflow_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                workflow_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_credentials_api_v1_credentials__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialResponse"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_api_v1_tools__get: {
        parameters: {
            query?: {
                status?: string | null;
                category?: string | null;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResponse"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tool_api_v1_tools__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_knowledge_base_documents_get: {
        parameters: {
            query?: {
                /** @description Filter by processing status */
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponseSchema"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recordings_api_v1_workflow_recordings__get: {
        parameters: {
            query?: {
                /** @description Filter by workflow ID */
                workflow_id?: number | null;
                /** @description Filter by TTS provider */
                tts_provider?: string | null;
                /** @description Filter by TTS model */
                tts_model?: string | null;
                /** @description Filter by TTS voice ID */
                tts_voice_id?: string | null;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingListResponseSchema"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_node_types_api_v1_node_types_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeTypesResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_type_api_v1_node_types__name__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeSpec"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
