// Display names for accent codes returned by the voice catalog.
//
// The catalog derives accent from a voice's locale country (e.g. "en-US" -> "us"),
// so the stored/filter value is an ISO 3166-1 alpha-2 country code. These are the
// human-readable accent labels shown in the UI; the underlying code stays the
// filter value. Unknown codes fall back to a capitalized form at the call site.
export const ACCENT_DISPLAY_NAMES: Record<string, string> = {
    us: "American",
    gb: "British",
    au: "Australian",
    ca: "Canadian",
    ie: "Irish",
    nz: "New Zealand",
    za: "South African",
    in: "Indian",
    bd: "Bangladeshi",
    sg: "Singaporean",
    my: "Malaysian",
    ph: "Filipino",
    id: "Indonesian",
    vn: "Vietnamese",
    th: "Thai",
    cn: "Chinese",
    jp: "Japanese",
    kr: "Korean",
    fr: "French",
    de: "German",
    ch: "Swiss",
    nl: "Dutch",
    it: "Italian",
    es: "Spanish",
    mx: "Mexican",
    co: "Colombian",
    bo: "Bolivian",
    br: "Brazilian",
    pt: "Portuguese",
    ru: "Russian",
    ua: "Ukrainian",
    pl: "Polish",
    cz: "Czech",
    sk: "Slovak",
    hu: "Hungarian",
    ro: "Romanian",
    bg: "Bulgarian",
    hr: "Croatian",
    gr: "Greek",
    ge: "Georgian",
    md: "Moldovan",
    se: "Swedish",
    no: "Norwegian",
    dk: "Danish",
    fi: "Finnish",
    tr: "Turkish",
    il: "Israeli",
    sa: "Saudi",
};
