import asyncio
import os
import sys

# Add project root to python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from api.db import db_client
from api.db.models import TelephonyConfigurationModel, TelephonyPhoneNumberModel
from api.services.telephony.providers.vobiz import _ensure_application_id
from api.services.telephony.factory import get_telephony_provider_by_id
from api.utils.common import get_backend_endpoints
from sqlalchemy.future import select

async def main():
    org_id = 2
    workflow_id = 9
    auth_id = "MA_P2FNGBN8"
    auth_token = "d7gBKu5hZhKdxelAzHFLS8yOY9rKfhLhQrqrIPE15BMg8WPV23wqEEpBgVQr5nXQ"
    phone_number = "918071583205"

    print("Configuring Vobiz for Organization 2...")
    
    # 1. Prepare credentials
    credentials = {
        "auth_id": auth_id,
        "auth_token": auth_token,
        "from_numbers": [phone_number],
        "application_id": None
    }
    
    # Ensure application ID is generated by calling Vobiz APIs
    print("Calling Vobiz to create/ensure application...")
    try:
        credentials = await _ensure_application_id(credentials)
        print(f"Generated/Verified credentials: {credentials}")
    except Exception as e:
        print(f"Error ensuring application ID: {e}")
        
    # 2. Check if a configuration exists for this provider in Org 2
    async with db_client.async_session() as session:
        # Clear default outbound on other configs in Org 2
        from sqlalchemy import update
        await session.execute(
            update(TelephonyConfigurationModel)
            .where(
                TelephonyConfigurationModel.organization_id == org_id,
                TelephonyConfigurationModel.is_default_outbound.is_(True)
            )
            .values(is_default_outbound=False)
        )
        
        # Look for existing config with name "Vobiz" or provider "vobiz"
        result = await session.execute(
            select(TelephonyConfigurationModel).where(
                TelephonyConfigurationModel.organization_id == org_id,
                TelephonyConfigurationModel.provider == "vobiz"
            )
        )
        cfg = result.scalars().first()
        
        if cfg:
            print(f"Found existing Vobiz config ID: {cfg.id}. Updating...")
            cfg.credentials = credentials
            cfg.is_default_outbound = True
        else:
            print("Creating new Vobiz config...")
            cfg = TelephonyConfigurationModel(
                organization_id=org_id,
                name="Vobiz Configuration",
                provider="vobiz",
                credentials=credentials,
                is_default_outbound=True
            )
            session.add(cfg)
            
        await session.commit()
        await session.refresh(cfg)
        config_id = cfg.id
        print(f"Vobiz configuration saved with ID: {config_id}")
        
        # 3. Create or update the TelephonyPhoneNumber
        from api.utils.telephony_address import normalize_telephony_address
        normalized = normalize_telephony_address(phone_number, country_hint="IN")
        print(f"Normalized number address: {normalized.canonical}")
        
        # Look for existing phone number for this address in Org 2
        result_num = await session.execute(
            select(TelephonyPhoneNumberModel).where(
                TelephonyPhoneNumberModel.organization_id == org_id,
                TelephonyPhoneNumberModel.address_normalized == normalized.canonical
            )
        )
        phone_row = result_num.scalars().first()
        
        if phone_row:
            print(f"Found existing phone number entry ID: {phone_row.id}. Updating...")
            phone_row.telephony_configuration_id = config_id
            phone_row.inbound_workflow_id = workflow_id
            phone_row.is_active = True
            phone_row.is_default_caller_id = True
        else:
            print("Creating new phone number entry...")
            phone_row = TelephonyPhoneNumberModel(
                organization_id=org_id,
                telephony_configuration_id=config_id,
                address=phone_number,
                address_normalized=normalized.canonical,
                address_type=normalized.address_type,
                country_code="IN",
                label="Vobiz Main Number",
                inbound_workflow_id=workflow_id,
                is_active=True,
                is_default_caller_id=True,
                extra_metadata={}
            )
            session.add(phone_row)
            
        await session.commit()
        await session.refresh(phone_row)
        print(f"Phone number configured successfully: {phone_row.address} (ID: {phone_row.id})")
        
        # 4. Sync inbound configuration on Vobiz provider
        print("Syncing inbound webhook configuration on Vobiz...")
        backend_endpoint, _ = await get_backend_endpoints()
        print(f"Inbound webhook URL: {backend_endpoint}/api/v1/telephony/inbound/run")
        
        provider = await get_telephony_provider_by_id(config_id, org_id)
        sync_res = await provider.configure_inbound(phone_row.address, f"{backend_endpoint}/api/v1/telephony/inbound/run")
        print(f"Sync result: ok={sync_res.ok}, message={sync_res.message}")

if __name__ == "__main__":
    asyncio.run(main())
